// src/components/SearchBar.vue
<script setup lang="ts">import { nextTick, onMounted, ref } from 'vue';

const props = defineProps<{
	modelValue: string,
	suggestions: string[]
}>();
const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void,
  (e: 'send', value: string): void
}>()

function targetValue(e: any) { return e.target.value; }

const selectedSuggestion = ref(1);
function suggestionUp() { selectedSuggestion.value = Math.max(selectedSuggestion.value - 1, 1); }
function suggestionDown() { selectedSuggestion.value = Math.min(selectedSuggestion.value + 1, props.suggestions.length); }
function acceptSuggestion(suggestion?: string) {
	const query = suggestion ?? props.suggestions[selectedSuggestion.value - 1];
	emit('update:modelValue', query);
	// emit('send', query);
}

const searchInput = ref<HTMLInputElement | null>(null);
onMounted(() => nextTick(() => searchInput.value?.focus()))

function send() {
	if(searchInput.value?.value !== '')
		searchInput.value?.blur();
	emit('send', props.modelValue);
}
</script>

<template lang="pug">
.search-bar
	input(
		ref="searchInput"
		type="search"
		placeholder="Search..."
		:value="modelValue"
		autocomplete="off"
		@input="emit('update:modelValue', targetValue($event).toLowerCase())"
		@keydown.enter="send()"
		@keydown.up="suggestionUp()"
		@keydown.down="suggestionDown()"
		@keydown.tab.prevent="acceptSuggestion()"
		onfocus="this.select();"
	)
	slot
	.suggestions(v-if="suggestions")
		.suggestion(
			v-for="suggestion, i of suggestions"
			:class="{ active: i + 1 == selectedSuggestion }"
			@click="acceptSuggestion(suggestion)"
		)
			span.tab-hint [tab]
			| {{suggestion}}
</template>

<style lang="scss">

.search-bar {
	display: flex;
	flex-flow: nowrap row;

	position: relative;

	box-sizing: border-box;
	width: 100%;
	max-width: 14cm;

	margin: 0;
	margin-inline: auto;

	font-size: 2em;

	background: #0002;
	border-radius: .5em;
	padding-inline: .3em;
	padding-block: .2em;

	transition: 400ms border-color;
	border: 1px solid transparent;
	&:focus-within {
		border-color: purple;
	}

	.suggestions {
		position: absolute;
		top: 100%;

		.suggestion {
			.tab-hint {
				font-size: .5em;
				opacity: 0;
				transition: opacity 200ms;
			}
			&.active {
				text-decoration: underline;
				.tab-hint {
					opacity: 100%;
				}
			}
		}
	}
	&:not(:focus-within) {
		.suggestions {
			display: none;
		}
	}

	* {
		font-size: inherit;
		margin: 0;
		padding-block: .1em;
		padding-inline: .1em;
		border-radius: 0;
	}
	input, button, select, a {
		background: none;
		border: none;
		outline: none;
	}
	button, a, select {
		height: 100%;
		width: 1.5em;
		border-radius: inherit;
		cursor: pointer;
		opacity: 20%;
		&:hover {
			opacity: 100%;
		}
	}
	select {
		appearance: none;
		width: 2em;
	}
	input[type="search"] {
		flex-grow: 1;
		width: 0;
	}
}
</style>

// src/lib/SearchBar.svelte
<script lang="ts">
import { SearchService } from "../SearchService";
import { debounce } from 'lodash';
import { push as pushRoute } from 'svelte-spa-router'

export let searchTerm = "";

const searchService = new SearchService();

let completions = [] as string[];

const fetchCompletions = debounce(async() => completions = await searchService.autocomplete(searchTerm), 100);
function updateCompletions() {
    completions = completions.filter(c => c.includes(searchTerm));
    fetchCompletions();
}

function keydown(e: KeyboardEvent) {
    if(e.key == 'Enter' && searchTerm.trim() !== '') {
        pushRoute(`/search/${searchTerm}`)
    }
}

</script>

<div class="search-bar">
    <div class="search">
        <button>✍️</button>
        <button>部</button>
        <div class="divider"></div>
        <input type="text"
            name="searchbox" id="searchbox"
            placeholder="Search..."
            bind:value={searchTerm}
            on:input={updateCompletions}
            on:blur={() => completions = []}
            on:keydown={keydown}
        >
        <button>🔍</button>
    </div>
    {#if completions.length > 0}
        <div class="auto-completions">
            {#each completions as completion}
                <div>{completion}</div>
            {/each}
        </div>
    {/if}
</div>

<style>
    .search-bar {
        position: relative;
        width: fit-content;
        font-size: 2rem;
    }
    .search {
        display: flex;
        flex-flow: nowrap row;

        height: 2.5rem;
        border: 1px solid white;
        border-radius: .5rem;
    }
    .search:focus-within {
        outline: 2px solid black;
    }
    .search>* {
        box-sizing: border-box;
        height: 100%;
        border: none;
        margin: 0;
        font-size: inherit;
        outline: none;
    }
    .divider {
        min-width: .2em;
        background: black;
    }

    .auto-completions {
        display: absolute;
        bottom: -100%;
        box-shadow: .1em .1em .1em .1em #0002;
        padding: 1em;
    }
</style>
