// src/lib/SearchBar.svelte
<script lang="ts">
import { SearchService } from "../SearchService";
import { debounce } from 'lodash';
import { push as pushRoute } from 'svelte-spa-router'

export let searchTerm = "";

const searchService = new SearchService();

let completions = [] as string[];

const fetchCompletions = debounce(async() => completions = await searchService.autocomplete(searchTerm), 100);
function updateCompletions() {
    completions = completions.filter(c => c.includes(searchTerm));
    fetchCompletions();
}

function keydown(e: KeyboardEvent) {
    if(e.key == 'Enter' && searchTerm.trim() !== '') {
        pushRoute(`/search/${searchTerm}`)
    }
}

</script>

<div class="search-bar">
    <div class="search">
        <button>✍️</button>
        <button>部</button>
        <div class="divider"></div>
        <input type="text"
            name="searchbox" id="searchbox"
            placeholder="Search..."
            bind:value={searchTerm}
            on:input={updateCompletions}
            on:blur={() => completions = []}
            on:keydown={keydown}
        >
        <button>🔍</button>
    </div>
    {#if completions.length > 0}
        <div class="auto-completions">
            {#each completions as completion}
                <div>{completion}</div>
            {/each}
        </div>
    {/if}
</div>

<style>
    .search-bar {
        position: relative;
        width: fit-content;
        font-size: 2rem;
    }
    .search {
        display: flex;
        flex-flow: nowrap row;

        height: 2.5rem;
        border: 1px solid white;
        border-radius: .5rem;
    }
    .search:focus-within {
        outline: 2px solid black;
    }
    .search>* {
        box-sizing: border-box;
        height: 100%;
        border: none;
        margin: 0;
        font-size: inherit;
        outline: none;
    }
    .divider {
        min-width: .2em;
        background: black;
    }

    .auto-completions {
        display: absolute;
        bottom: -100%;
        box-shadow: .1em .1em .1em .1em #0002;
        padding: 1em;
    }
</style>

// code/web/src/components/SearchBar.vue
<script setup lang="ts">
import { onKeyboardShortcut } from '@/util/OnKeyboardShortcut';
import { onScrolledUsingTouch } from '@/util/OnScrolledUsingTouch';
import { onTabFocusChange } from '@/util/OnTabFocusChange';
import { ref } from 'vue';

const props = defineProps<{
	modelValue: string,
}>();
const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void,
  (e: 'send', value: string): void
}>()

function targetValue(e: any) { return e.target.value; }

const searchInput = ref<HTMLInputElement | null>(null);
function focus() {
	searchInput.value?.focus();
	(navigator as any).virtualKeyboard?.show();
}
function blur() { searchInput.value?.blur(); }
function send() {
	searchInput.value?.select();
	emit('send', props.modelValue);
}

onKeyboardShortcut({
	'alt+f,alt+u': () => {
		if(searchInput.value === document.activeElement)
			return false;
		focus();
	}
});

onScrolledUsingTouch(() => searchInput.value?.blur());

onTabFocusChange(hasFocus => {
	if(hasFocus)
		setTimeout(() => focus(), 100); // Need a timeout so the click event (from clicking into the tab) and doesn't immediately steal the focus back
	else
		blur();
});

</script>

<template lang="pug">
.search-bar
	input(type="search" ref="searchInput"
		placeholder="Search..."

		:value="modelValue"
		@keydown.enter.prevent="emit('update:modelValue', targetValue($event).toLowerCase()); send()"

		onfocus="this.select()"

		autofocus
		autocomplete="off"
		autocapitalize="none"
	)
	slot
</template>

<style lang="scss">

.search-bar {
	display: flex;
	flex-flow: nowrap row;

	position: relative;

	box-sizing: border-box;
	width: 14cm;
	max-width: calc(100vw - .5em);
	margin-block: .2em;
	margin-inline: auto;

	font-size: 2em;

	background: var(--background2);
	border-radius: .5em;
	padding-inline: .3em;
	padding-block: .2em;

	transition: 400ms border-color;
	border: var(--outline-width) solid var(--neutral1);
	&:focus-within {
		border-color: var(--accent1);
	}

	* {
		font-size: inherit;
		margin: 0;
		padding-block: .1em;
		padding-inline: .1em;
		border-radius: 0;
	}
	input, button, select, a {
		background: none;
		border: none;
		outline: none;
	}
	button, a, select {
		height: 100%;
		width: 1.5em;
		border-radius: inherit;
		text-decoration: none;
		cursor: pointer;
		color: var(--text-muted2);
		transition: color 200ms;
		&:hover {
			color: var(--text1);
		}
	}
	select {
		appearance: none;
		width: 2em;
	}
	input[type="search"] {
		flex-grow: 1;
		width: 0;
	}
}
</style>
